# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardimg', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('cardtitle', models.CharField(max_length=200)),
                ('cardtext', models.TextField()),
                ('carddescription', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newsinline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField(max_length=400)),
            ],
            options={
                'ordering': ('-time',),
            },
        ),
    ]
